### ISSUE TITLE
Jest encountered an unexpected token 

### ISSUE THREAD

**Issue by a1exymoroz** [pnp/pnpjs#1058]
Jest doesn't work with import { Web } from "@pnp/sp/webs";

```
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    ....node_modules\@pnp\sp\webs\index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { Web } from "./types";
                                                                                                    ^

    SyntaxError: Unexpected token {



      at Runtime.createScriptFromCode (../node_modules/jest-runner/node_modules/jest-runtime/build/index.js:1059:14)
      at Object.<anonymous> (webparts/locationsManagement/components/list/use.list.tsx:747:40)
```

### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 2.0.2 ]

Please specify what version(s) of SharePoint you are targeting: [ 1.10.0 ]

### Expected / Desired Behavior / Question
Tests are working

### Steps to Reproduce
package.json
```
{
  "name": "locations",
  "version": "0.0.1",
  "private": true,
  "main": "lib/index.js",
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "start": "gulp serve",
    "type-lint": "tsc --noEmit -p tsconfig.json",
    "package": "gulp version-sync && gulp bundle --ship && gulp package-solution --ship",
    "lint": "tslint --fix -c ./tslint.json 'src/**/*{.ts,.tsx}'",
    "prettier": "prettier --config .prettierrc.yaml --write src/**/*.ts src/**/*.tsx",
    "commit": "git-cz",
    "postversion": "gulp version-sync",
    "test": "./node_modules/.bin/jest --config ./config/jest.config.json",
    "test:watch": "./node_modules/.bin/jest --config ./config/jest.config.json --watchAll"
  },
  "husky": {
    "hooks": {
      "pre-commit": "npm run prettier",
      "pre-push": "npm run type-lint && npm run lint"
    }
  },
  "dependencies": {
    "@microsoft/sp-core-library": "1.10.0",
    "@microsoft/sp-lodash-subset": "1.10.0",
    "@microsoft/sp-office-ui-fabric-core": "1.10.0",
    "@microsoft/sp-property-pane": "1.10.0",
    "@microsoft/sp-webpart-base": "1.10.0",
    "@pnp/common": "^2.0.2",
    "@pnp/logging": "^2.0.2",
    "@pnp/odata": "^2.0.2",
    "@pnp/sp": "^2.0.2",
    "@types/es6-promise": "0.0.33",
    "@types/react": "16.8.8",
    "@types/react-dom": "16.8.3",
    "@types/webpack-env": "1.13.1",
    "office-ui-fabric-react": "^7.88.1",
    "react": "16.8.5",
    "react-dom": "16.8.5"
  },
  "devDependencies": {
    "@microsoft/rush-stack-compiler-3.3": "0.3.5",
    "@microsoft/sp-build-web": "1.10.0",
    "@microsoft/sp-module-interfaces": "1.10.0",
    "@microsoft/sp-tslint-rules": "1.10.0",
    "@microsoft/sp-webpart-workbench": "1.10.0",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "@voitanos/jest-preset-spfx-react16": "^1.3.2",
    "ajv": "~5.2.2",
    "commitizen": "^4.0.3",
    "cz-conventional-changelog": "^3.0.2",
    "gulp": "~3.9.1",
    "husky": "^4.2.0",
    "jest": "^25.1.0",
    "prettier": "^1.19.1",
    "ts-jest": "^25.2.0",
    "tslint": "^6.0.0",
    "typescript": "^3.7.5"
  },
  "resolutions": {
    "@types/react": "16.8.8"
  },
  "config": {
    "commitizen": {
      "path": "cz-conventional-changelog"
    }
  }
}
```
jest.confi.json
```
{
  "rootDir": "../src",
  "collectCoverage": true,
  "coverageDirectory": "<rootDir>/../temp/test",
  "coverageReporters": [
    "json",
    "lcov",
    "text-summary"
  ],
  "moduleFileExtensions": [
    "ts",
    "tsx",
    "js",
    "json"
  ],
  "moduleNameMapper": {
    "\\.(css|scss)$": "identity-obj-proxy",
    "^resx-strings/en-us.json": "<rootDir>/node_modules/@microsoft/sp-core-library/lib/resx-strings/en-us.json",
    "office-ui-fabric-react/lib/(.*)$": "office-ui-fabric-react/lib-commonjs/$1"
  },
  "setupFiles": [
    "raf/polyfill",
    "@voitanos/jest-preset-spfx-react16/jest.enzyme.js"
  ],
  "snapshotSerializers": [
    "enzyme-to-json/serializer"
  ],
  "testMatch": [
    "**/src/**/*.(spec|test).+(ts|js)?(x)",
    "**/__tests__/**/*.(spec|test).+(ts|js)?(x)"
  ],
  "transform": {
    "^.+\\.(ts|tsx)$": "ts-jest"
  }
}

```
Component.tsx
```
import { Web } from "@pnp/sp/webs";
```

**Comment by koltyakov** [comment]
Did you try importing in such a manner?

```typescript
import { sp } from "@pnp/sp";
import "@pnp/sp/webs";
```

**Comment by a1exymoroz** [comment]
The same problem

**Comment by koltyakov** [comment]
Can you share a bare minimal repro repo which we can pull, restore and check?

**Comment by a1exymoroz** [comment]
https://github.com/a1exymoroz/spfx-jest

**Comment by koltyakov** [comment]
I guess that a quick solution would be temporary switching to `@pnp/sp-commonjs` or configuring Jest to use ES6 modules. As `@voitanos/jest-preset-spfx-react16` is used, maybe @andrewconnell knows a trick?

**Comment by chris-mullins** [comment]
I played around a bit with the configuration trying to get this to work, but did not get very far.  I can confirm that using the commonjs import allowed me to get my tests working though.
`import { sp } from "@pnp/sp-commonjs"`

**Comment by andrewconnell** [comment]
@koltyakov 
> maybe @andrewconnell knows a trick

Nope... unfortunately I don't. I've run into the same issue. Nothing special with the preset I created, it just simplifies the configuration.

**Comment by patrick-rodgers** [comment]
Going to close this as it is external to this library. Node just doesn't handle es modules well which is why we took the step of also publishing commonjs specific modules. I know this isn't ideal for testing your code before deployment. You might see if you can configure it such that the code is transpiled before testing - but I don't know jest so am not much help. Thanks!
