### ISSUE TITLE
Error @pnp/sp - SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by anderseide** [pnp/pnpjs#1168]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: 2.0.4

Please specify what version(s) of SharePoint you are targeting: SharePoint Online

### Expected / Desired Behavior / Question
Should be possible to import this library in a Azure Function or just a local nodejs script, according to documentation.

### Observed Behavior

```
Exception: Worker was unable to load function TestFunction: 'SyntaxError: Unexpected token 'export''
Stack: ...\node_modules\@pnp\sp\index.js:1
export { SharePointQueryableInstance, SharePointQueryableCollection, SharePointQueryable, spInvokableFactory, } from "./sharepointqueryable";
^^^^^^

SyntaxError: Unexpected token 'export'
    at Module._compile (internal/modules/cjs/loader.js:895:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (...\TestFunction\index.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32).
```

### Steps to Reproduce
Getting the same error regardless of importing this in a Azure Function or local script. Also if I use this library in a typescript enabled Azure Function, and the example at https://pnp.github.io/pnpjs/sp/#getting-started-nodejs

Easily reproducible by following this guide, https://simonagren.github.io/azurefunction-v2-pnpjs/.

Getting the exact same error when just running this code in node

```
// file index.js
const sp = require("@pnp/sp")
require("@pnp/sp/webs")
const SPFetchClient = require("@pnp/nodejs");

sp.setup({
    sp: {
        fetchClientFactory: () => {
            return new SPFetchClient("xxx", "xxx", "xxx");
        },
    },
});

sp.web.select("Title")().then(w => {

    console.log(`Web Title: ${w.Title}`);
});
```

node index.js

**Comment by koltyakov** [comment]
This is not a bug, but a by design decision. A Node.js project should be configured to use ES6 modules, or @pnp/*-commonjs versions can be used instead.

**Comment by anderseide** [comment]
Thanks for the quick reply! When I tried to use ES6 imports, I got the samme error. Example below is the code used when Azure Functions is configured to use TypeScript

index.ts
```
import { AzureFunction, Context, HttpRequest } from "@azure/functions"
import { sp } from '@pnp/sp';
import "@pnp/sp/webs";
import { SPFetchClient } from '@pnp/nodejs';

const httpTrigger: AzureFunction = async function (context: Context, req: HttpRequest): Promise<void> {
    context.log('HTTP trigger function processed a request.');
    
    const SpSiteAddress = process.env['SPSiteAddress']
    const PnpAppId = process.env['PnPAppId'];
    const PnpAppSecret = process.env['PnPAppSecret'];

    sp.setup({
        sp: {
            fetchClientFactory: () => {
                return new SPFetchClient(SpSiteAddress, PnpAppId, PnpAppSecret);
            },
        },
    });

    sp.web.select("Title")().then(w => {
        context.log(`Web Title: ${w.Title}`);
    });

    context.res = {
        // status: 200, /* Defaults to 200 */
        body: "Go see the log"
    }
};

export default httpTrigger;
```

tsconfig.js (Default setup when creating a Azure Function App that uses typescript)
```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "outDir": "dist",
    "rootDir": ".",
    "sourceMap": true,
    "strict": false
  }
}
```

A more complete error log
```
require() of LOCALPATH\node_modules\@pnp\sp\index.js from LOCALPATH\dist\TestTrigger\index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
[20.04.2020 13:14:38] Result: Failure
Exception: Worker was unable to load function TestTrigger: 'SyntaxError: Unexpected token 'export''
Stack: LOCALPATH\node_modules\@pnp\sp\index.js:1
export { SharePointQueryableInstance, SharePointQueryableCollection, SharePointQueryable, spInvokableFactory, } from "./sharepointqueryable";
^^^^^^

SyntaxError: Unexpected token 'export'
    at Module._compile (internal/modules/cjs/loader.js:895:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (LOCALPATH\dist\TestTrigger\index.js:12:14)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32).
[20.04.2020 13:14:38] Instead rename LOCALPATH\node_modules\@pnp\sp\index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from LOCALPATH\node_modules\@pnp\sp\package.json.
```

**Comment by koltyakov** [comment]
But it's `commonjs` which is used, so ES6 modules are not expected in node_modules with such a setup:

![image](https://user-images.githubusercontent.com/7816483/79756605-8bc10c00-8323-11ea-87a9-6a636cf647e5.png)

My suggestion was to import these guys correspondingly:

```typescript
import { sp } from '@pnp/pnpjs-commonjs';
import { SPFetchClient } from '@pnp/nodejs-commonjs';
```

**Comment by koltyakov** [comment]
@anderseide please check this page https://pnp.github.io/pnpjs/nodejs-support/#commonjs-libraries, it contains some elaborations regarding Node.js use case.

**Comment by anderseide** [comment]
Thanks! Tried that one earlier and failed, but just realized that it's another error message.

```
Exception: Worker was unable to load function TestTrigger: 'SyntaxError: Cannot use import statement outside a module'
Stack: LOCALPATH\node_modules\@pnp\sp\webs\index.js:1
import { Web } from "./types";
```

Removing `import "@pnp/sp/webs";` from the code, solved it, but I'm now getting a connection timeout. Not sure what that import does, but I'll give docs another try :)
