### ISSUE TITLE
[Bug] Large file downloading from share point raise RangeError

### ISSUE THREAD

**Issue by tobyatgithub** [pnp/pnpjs#1354]
### Category
- [x] Enhancement
- [x] Bug
- [x] Question

### Version

Please specify what version of the library you are using: [core-js@2.6.10]

Please specify what version(s) of SharePoint you are targeting: [SharePoint online]

### Expected / Desired Behavior / Question
Download the zip file (about 4.5GB) into the specified path location.

### Observed Behavior
```
buffer.js:224
    throw err;
    ^

RangeError: "size" argument must not be larger than 2147483647
    at Function.Buffer.allocUnsafe (buffer.js:253:3)
    at Function.Buffer.concat (buffer.js:441:23)
    at Request.<anonymous> (/usr/local/lib/node_modules/@pnp/office365-cli/node_modules/request/request.js:1133:30)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/@pnp/office365-cli/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
```

### Steps to Reproduce
Hi guys, first time to raise an issue here. Hope I'm doing it correctly.
I was trying to make a pipeline for downloading large zip data file from sharepoint online.
I tested with smaller zip files and I worked fine.
But when I tried on a larger 4.5 GB zip file it failed.
I searched online and it seems this error comes from the js buffer which has a limitation about 2.14GB

I'm wondering will there be a fix soon? or maybe some methods to bypass this 2GB limitation?

Thank you very much!
(related stackoverflow I found: https://stackoverflow.com/questions/44994767/javascript-read-large-files-failed)

**Comment by patrick-rodgers** [comment]
I think you may have wanted to post this here: https://github.com/pnp/cli-microsoft365/issues? If so I can transfer it.

**Comment by tobyatgithub** [comment]
Hi Patrick, I think you are right! Sorry for misplacing this issue. It will be great if you can transfer it! Thank you and appreciate it :O

**Comment by juliemturner** [comment]
No worries, moving it for you now!
