### ISSUE TITLE
Banner image not working as expected.

### ISSUE THREAD

**Issue by PrathyushP95** [pnp/pnpjs#1369]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.7]

Please specify what version(s) of SharePoint you are targeting: [2016]

Hi,

I'm trying to set banner image to my modern pages using setBannerImage('/sites/dev/relative/path/to/image.jpg').

Please find the code snippet,

```
const ClientsidePageFromFile = require("@pnp/sp-commonjs/clientside-pages").ClientsidePageFromFile;
const ClientsideText = require('@pnp/sp-commonjs/clientside-pages').ClientsideText;
const ClientsideWebpart = require('@pnp/sp-commonjs/clientside-pages').ClientsideWebpart;
const sp = require('@pnp/sp-commonjs').sp;
const SPFetchClient = require('@pnp/nodejs-commonjs').SPFetchClient;

exports.handler = async (event) => {
sp.setup({
    sp: {
      fetchClientFactory: () => {
        return new SPFetchClient('https://domain.sharepoint.com/sites/dev', 'client_id','client_secret');
      },
    },
  });
let page = await sp.web.addClientsidePage('sample-test', 'Test Banner', 'Article');
page.addSection().addControl(new ClientsideText("@pnp/sp is a great library!"));
const file = await sp.web.getFileByServerRelativeUrl("/sites/dev/samplelib/4th-doc-4.jpg").select("ServerRelativeUrl")();
console.log(file.ServerRelativeUrl)
page.setBannerImage(file.ServerRelativeUrl);
await page.save();
};
```

This gives me below error.
```
ERROR Invoke Error {"errorType":"Error","errorMessage":"Error making HttpClient request in queryable [400] Bad Request ::> {\"odata.error\":{\"code\":\"-1, Microsoft.SharePoint.Client.InvalidClientQueryException\",\"message\":{\"lang\":\"en-US\",\"value\":\"Invalid request.\"}}}\r","response":{"size":0,"timeout":0},"status":400,"statusText":"Bad Request","isHttpRequestError":true,"stack":["Error: Error making HttpClient request in queryable [400] Bad Request ::> {\"odata.error\":{\"code\":\"-1, Microsoft.SharePoint.Client.InvalidClientQueryException\",\"message\":{\"lang\":\"en-US\",\"value\":\"Invalid request.\"}}}\r"," at new HttpRequestError (/opt/nodejs/node_modules/@pnp/odata-commonjs/parsers.js:133:28)"," at Function. (/opt/nodejs/node_modules/@pnp/odata-commonjs/parsers.js:148:47)"," at step (/opt/nodejs/node_modules/tslib/tslib.js:140:27)"," at Object.next (/opt/nodejs/node_modules/tslib/tslib.js:121:57)"," at fulfilled (/opt/nodejs/node_modules/tslib/tslib.js:111:62)"," at processTicksAndRejections (internal/process/task_queues.js:97:5)"]}

ERROR Unhandled Promise Rejection {"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: Error making HttpClient request in queryable [400] Bad Request ::> {\"odata.error\":{\"code\":\"-1, Microsoft.SharePoint.Client.InvalidClientQueryException\",\"message\":{\"lang\":\"en-US\",\"value\":\"Invalid request.\"}}}\r","reason":{"errorType":"Error","errorMessage":"Error making HttpClient request in queryable [400] Bad Request ::> {\"odata.error\":{\"code\":\"-1, Microsoft.SharePoint.Client.InvalidClientQueryException\",\"message\":{\"lang\":\"en-US\",\"value\":\"Invalid request.\"}}}\r","response":{"size":0,"timeout":0},"status":400,"statusText":"Bad Request","isHttpRequestError":true,"stack":["Error: Error making HttpClient request in queryable [400] Bad Request ::> {\"odata.error\":{\"code\":\"-1, Microsoft.SharePoint.Client.InvalidClientQueryException\",\"message\":{\"lang\":\"en-US\",\"value\":\"Invalid request.\"}}}\r"," at new HttpRequestError (/opt/nodejs/node_modules/@pnp/odata-commonjs/parsers.js:133:28)"," at Function. (/opt/nodejs/node_modules/@pnp/odata-commonjs/parsers.js:148:47)"," at step (/opt/nodejs/node_modules/tslib/tslib.js:140:27)"," at Object.next (/opt/nodejs/node_modules/tslib/tslib.js:121:57)"," at fulfilled (/opt/nodejs/node_modules/tslib/tslib.js:111:62)"," at processTicksAndRejections (internal/process/task_queues.js:97:5)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: Error: Error making HttpClient request in queryable [400] Bad Request ::> {\"odata.error\":{\"code\":\"-1, Microsoft.SharePoint.Client.InvalidClientQueryException\",\"message\":{\"lang\":\"en-US\",\"value\":\"Invalid request.\"}}}\r"," at process. (/var/runtime/index.js:35:15)"," at process.emit (events.js:315:20)"," at processPromiseRejections (internal/process/promises.js:209:33)"," at processTicksAndRejections (internal/process/task_queues.js:98:32)"]}
```
My console.log(file.ServerRelativeUrl) gives me '/sites/dev/samplelib/4th-doc-4.jpg'.

The image is under same site collection and when i tried to manually set the banner image it worked.

Can someone please help me to resolve this issue?

**Comment by PrathyushP95** [comment]
Hi Team, I've updated this issue with more details.

**Comment by patrick-rodgers** [comment]
Having a chance to come back to this item - I am not able to duplicate the issue. My sample code:

```TypeScript
import { SPFetchClient } from "@pnp/nodejs";
import { sp } from "@pnp/sp";
import "@pnp/sp/webs";
import "@pnp/sp/clientside-pages";
import { getRandomString } from '@pnp/common';

// configure your node options
sp.setup({
    sp: {
        fetchClientFactory: () => {
            return new SPFetchClient(settings.testing.sp.url, settings.testing.sp.id, settings.testing.sp.secret);
        },
    },
});

const w = await sp.web.addClientsidePage(`testpage${getRandomString(4)}`, `Test Page`);

// tested with both this:
w.setBannerImage("/sites/dev/SiteAssets/WP_20150711_21_54_38_Pro.jpg");

// and this (in individual tests) to see if there was a problem adding the file from the root of the site collection in a child site
// or a problem with adding images from within the child site.
// w.setBannerImage("/sites/dev/6b6baf3e-e344-41e3-aa42-c47d4ad1be24/SiteAssets/WP_20150711_21_54_38_Pro.jpg");

await w.save(true);
```

So far as I can tell everything is working as expected.

**Comment by patrick-rodgers** [comment]
Going to close as I can't duplicate the issue as you reported. If you are still having problems please open a new issue and ref this one including any additional information. Thanks!
