### ISSUE TITLE
baseUrl: beta uses https://graph.microsoft.com/beta/v1.0/

### ISSUE THREAD

**Issue by nodevar** [pnp/pnpjs#1693]
Im having issues switching to beta graph endpoints.

### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    2.4.0     ]

Please specify what version(s) of SharePoint you are targeting: [ Graph API        ]

### Expected / Desired Behavior / Question
i except to switch to beta endpoints with **baseUrl: "beta"**

  ```
graph.setup({
    graph: {
      baseUrl: "beta",
      fetchClientFactory: () => {
        return new AdalFetchClient(TENANT, ID,SECRET);
      },
    },
  });
```

### Observed Behavior
```
Error: Error making HttpClient request in queryable [400] Bad Request ::> {
  "error": {
    "code": "BadRequest",
    "message": "Resource not found for the segment 'v1.0'.",
    "innerError": {
      "date": "2021-04-10T02:53:50",
      "request-id": "7df2m2b-2c6f-4659-9516-dedd0391b3eb",
      "client-request-id": "74dfm12b-2c6f-4659-9516-dedd0391b3eb"
    }
  }
}
    at new HttpRequestError (D:\home\site\wwwroot\node_modules\@pnp\odata-commonjs\parsers.js:133:28)
    at Function.<anonymous> (D:\home\site\wwwroot\node_modules\@pnp\odata-commonjs\parsers.js:148:47)
    at step (D:\home\site\wwwroot\node_modules\@pnp\odata-commonjs\node_modules\tslib\tslib.js:143:27)
    at Object.next (D:\home\site\wwwroot\node_modules\@pnp\odata-commonjs\node_modules\tslib\tslib.js:124:57)
    at fulfilled (D:\home\site\wwwroot\node_modules\@pnp\odata-commonjs\node_modules\tslib\tslib.js:114:62)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  response: Response {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: false, error: null },
    [Symbol(Response internals)]: {
      url: 'https://graph.microsoft.com/beta/v1.0/subscriptions',
      status: 400,
      statusText: 'Bad Request',
      headers: [Headers],
      counter: undefined
    }
  },
  status: 400,
  statusText: 'Bad Request',
  isHttpRequestError: true
}

```
### Steps to Reproduce
use baseUrl while setup graph context

**Comment by nodevar** [comment]
I start to think that im using this not the right way but probably somebody can help me out here.

In my opinion baseUrl is doing what it is susposed to do since i can see in toabsoluturl.js in fact that baseUrl is valid but canidateUrl is with a v1.0/ prefix. 

So function toAbsolutUrl is called and returns baseUrl, and candidateUrl combined:

```
  baseUrl = (_a = runtime.get("graph")) === null || _a === void 0 ? void 0 : _a.baseUrl;
                    if (!common_1.stringIsNullOrEmpty(baseUrl)) {
                        // base url specified either with baseUrl of spfxContext config property
                        console.debug(baseUrl);
                        console.debug(candidateUrl);
                        candidateUrl = candidateUrl.substring(5);
                        console.debug(candidateUrl);
                        return [2 /*return*/, common_1.combine(baseUrl, candidateUrl)];


```

results: 
021-04-10T14:04:09.550 [Information] beta
2021-04-10T14:04:09.550 [Information] v1.0/users/

Or while subscribe: 
2021-04-10T14:04:10.008 [Information] beta
2021-04-10T14:04:10.008 [Information] v1.0/subscriptions/

if i remove v1.0/ from candidateUrl everything works fine. 
context:
```function toAbsoluteUrl(candidateUrl, runtime) {
    var _a, _b, _c;
    if (runtime === void 0) { runtime = common_1.DefaultRuntime; }
    return tslib_1.__awaiter(this, void 0, void 0, function () {
        var baseUrl, spFxContext, client, e_1;
        return tslib_1.__generator(this, function (_d) {
            switch (_d.label) {
                case 0:
                    if (common_1.isUrlAbsolute(candidateUrl)) {
                        // if we are already absolute, then just return the url
                        return [2 /*return*/, candidateUrl];
                    }
                    baseUrl = (_a = runtime.get("graph")) === null || _a === void 0 ? void 0 : _a.baseUrl;
                    if (!common_1.stringIsNullOrEmpty(baseUrl)) {
                        // base url specified either with baseUrl of spfxContext config property
                        console.debug(baseUrl);
                        console.debug(candidateUrl);
                        candidateUrl = candidateUrl.substring(5);
                        console.debug(candidateUrl);
                        return [2 /*return*/, common_1.combine(baseUrl, candidateUrl)];
                    }````

**Comment by patrick-rodgers** [comment]
Hi @nodevar,

This is an area where we can improve the docs, and I understand why you took the approach you did, but the "baseUrl" isn't intended to be used like that in the setup method. I believe you a likely being confused by a [similarly named option in isolated runtimes](https://pnp.github.io/pnpjs/concepts/configuration/#graphcreateisolated). This is our fault and not yours and one of the many reasons we are working to clean up our configuration story for v3.

If you want to switch the target of graph calls to either v1.0 or beta you can use the 'setEndpoint' method available on all graph queryable objects. Usage is:

```TypeScript
const betaResult = await graph.me.setEndpoint("beta")();

const v1Result = await graph.me.setEndpoint("v1.0")();
```

I added this info to the graph docs page which will be published with the upcoming release. Sorry for the confusion here.
