### ISSUE TITLE
Unable to add Tags to page

### ISSUE THREAD

**Issue by iamrealvinod** [pnp/pnpjs#1810]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.5.0]

Please specify what version(s) of SharePoint you are targeting: [2016]

### Expected / Desired Behavior / Question
*Expecting to add a tag to site pages.*

### Observed Behavior
*Getting Error: Error making HttpClient request in queryable [403] Forbidden*

### Steps to Reproduce

```
let termstore = await sp.termStore;
console.log(termstore);
```
output:
```
[Function] class_1 {
  _data: {
    cloneParentWasCaching: false,
    options: { headers: {} },
    parentUrl: '',
    parser: ODataParser {},
    query: Map {},
    url: '_api/v2.1/termstore',
    useCaching: false
  },
  _runtime: Runtime {
    _v: Map {
      '__isDefault__' => true,
      'defaultCachingStore' => 'session',
      'defaultCachingTimeoutSeconds' => 60,
      'globalCacheDisable' => false,
      'enableCacheExpiration' => false,
      'cacheExpirationIntervalMilliseconds' => 750,
      'spfxContext' => null,
      'ie11' => false,
      'sp' => [Object]
    }
  },
  _forceCaching: false,
  [Symbol(43f7a601)]: [
    {
      getStream: [Function: getStream],
      setStreamContentChunked: [Function: setStreamContentChunked]
    },
    { addChunked: [Function: addChunked] }
  ]
}
```
```
let termdetails = await sp.termStore.groups.getById(termgrp_id).sets.getById(termset_id).getTermById(term_id)();
console.log(termgrp);
```
output:
```
Error: Error making HttpClient request in queryable [403] Forbidden ::> {
    "error": {
        "code": "accessDenied",
        "message": "The current user has insufficient permissions to perform this operation."
    }
}
    at new HttpRequestError (/opt/nodejs/node_modules/@pnp/odata-commonjs/parsers.js:133:28)
    at Function.<anonymous> (/opt/nodejs/node_modules/@pnp/odata-commonjs/parsers.js:148:47)
    at step (/opt/nodejs/node_modules/tslib/tslib.js:143:27)
    at Object.next (/opt/nodejs/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/opt/nodejs/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  response: Response {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: false, error: null },
    [Symbol(Response internals)]: {
      url: 'https://{domain}.sharepoint.com/sites/{site_name}/_api/v2.1/termstore/groups/{group_id}/sets/{set_id}/terms/{term_id}',
      status: 403,
      statusText: 'Forbidden',
      headers: [Headers],
      counter: undefined
    }
  },
  status: 403,
  statusText: 'Forbidden',
  isHttpRequestError: true
}
```

**Comment by patrick-rodgers** [comment]
Hi, as this is a security error can you share some information on how you are doing authentication? Don't share any usernames/passwords - but the method you are using the auth? Thanks!

**Comment by iamrealvinod** [comment]
> Hi, as this is a security error can you share some information on how you are doing authentication? Don't share any usernames/passwords - but the method you are using the auth? Thanks!

Hello, We were able to add tags to web pages prior to 24th May. It suddenly stopped working with above-mentioned error. We had not made any code changes at our end. 

We are using client id and client secret for authentication. And we are able to create pages but we are unable to add tags to the page.

Here is a sample code:
```
sp.setup({
    sp: {
      fetchClientFactory: () => {
        return new SPFetchClient(process.env.site_domain + page_path, process.env.client_id, process.env.client_secret);
      },
    },
  });
```

**Comment by patrick-rodgers** [comment]
Has you ACS identity expired? IF there are no changes and auth suddenly failed that might be it. Would when you have a chance look to move to [MSAL auth](https://pnp.github.io/pnpjs/authentication/server-nodejs/#msal) as possible, ACS is starting to have limitations.

If your code hasn't changed and our code hasn't changed I do think checking for expired ACS identity is the way to go. Or register a fresh one.

**Comment by PrathyushP95** [comment]
Hi @patrick-rodgers , We tried the above [MSAL auth](https://pnp.github.io/pnpjs/authentication/server-nodejs/#call-sharepoint) which still gives an error for us. Please help us to sort this out.

We first created the certificate files as mentioned in the doc and uploaded that cert in the newly created Azure Active Directory application.

Please find the below code for reference.

```
const buffer = readFileSync("/path/to/key.pem");
sp.setup({
   sp: {
     baseUrl: "https://tenent.sharepoint.com/sites/dev",
     fetchClientFactory: () => {
       return new MsalFetchClient({
        auth: {
           authority: "https://login.microsoftonline.com/tenant_id/",
           clientCertificate: {
             thumbprint: "thumbprint_from_AAD",
             privateKey: buffer.toString(),
          },
          clientId: "AAD_client_id",
         }
       }, ["https://tenant.sharepoint.com/.default"]);
     },
   },
   });
```
Error
```
{
    "errorType": "Error",
    "errorMessage": "Error making HttpClient request in queryable [401] Unauthorized ::> {\"error_description\":\"ID3035: The request was not valid or is malformed.\"}",
    "response": {
        "size": 0,
        "timeout": 0
    },
    "status": 401,
    "statusText": "Unauthorized",
    "isHttpRequestError": true,
    "stack": [
        "Error: Error making HttpClient request in queryable [401] Unauthorized ::> {\"error_description\":\"ID3035: The request was not valid or is malformed.\"}",
        "    at new HttpRequestError (/opt/nodejs/node_modules/@pnp/odata-commonjs/parsers.js:133:28)",
        "    at Function.<anonymous> (/opt/nodejs/node_modules/@pnp/odata-commonjs/parsers.js:148:47)",
        "    at step (/opt/nodejs/node_modules/tslib/tslib.js:143:27)",
        "    at Object.next (/opt/nodejs/node_modules/tslib/tslib.js:124:57)",
        "    at fulfilled (/opt/nodejs/node_modules/tslib/tslib.js:114:62)",
        "    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
    ]
}

```

**Comment by patrick-rodgers** [comment]
This is still an auth error so we can't provide a lot of assistance. If you try and run it locally does it work? If yes, perhaps the issue is with Azure config? Or perhaps you haven't granted the perms to the AAD application.

**Comment by iamrealvinod** [comment]
This was permission issue, which we managed to finally fix.
