### ISSUE TITLE
Updating URL field on a list not working using PnPjs V3 - '__metadata' does not exist on type 'SP.FieldUrlValue'

### ISSUE THREAD

**Issue by antoniocguillen** [pnp/pnpjs#2153]
### Category
- [ ] Enhancement
- [X ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   3.1      ]

Please specify what version(s) of SharePoint you are targeting: [   1.14      ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
Updating a sp list item URL field should work.

### Observed Behavior

Uncaught (in promise) Error: Error making HttpClient request in queryable [400]  ::> {"odata.error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"en-US","value":"The property '__metadata' does not exist on type 'SP.FieldUrlValue'. Make sure to only use property names that are defined by the type."}}}
    at Function.init (parsers.js:85:1)
    at async Proxy.errorCheck (parsers.js:33:1)
    at async Proxy.<anonymous> (moments.js:31:1)
    at async queryable.js:104:1

### Steps to Reproduce
I copied this from the Chrome network tab (copied as fetch statement):
`
fetch("https://mytenant/sites/NA-BlankTemplate1/_api/web/lists/getByTitle('Main%20Articles')/items(11)", {
  "headers": {
    "accept": "application/json",
    "accept-language": "en-US,en;q=0.9",
    "cache-control": "max-age=0",
    "content-type": "application/json;charset=utf-8",
    "if-match": "*",
    "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"99\", \"Google Chrome\";v=\"99\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "x-clientservice-clienttag": "PnPCoreJS:3.1.0:w.l.g.items(11)",
    "x-http-method": "MERGE",
    "x-requestdigest": "0x72E47BF97A7B362FB4F3C7ADBD6F5329E2042974D07CB15F8480C26964DC40AD2FBF8CAB769D21D8EB055DFD17EA59A171A1E0C8E81F5941ACC58C37F671A185,11 Mar 2022 18:13:10 -0000"
  },
  "referrer": "https://mytenant/sites/NA-BlankTemplate1/Lists/Main%20Articles/AllItems.aspx",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "{\"Page_x0020_Image\":{\"__metadata\":{\"type\":\"SP.FieldUrlValue\"},\"Description\":\"648617500\",\"Url\":\"https://cdn.hubblecontent.osi.office.net/m365content/publish/006d27b5-ce41-4f23-b65e-df986bb9947b/648617500.jpg\"},\"__metadata\":{\"type\":\"SP.ListItem\"}}",
  "method": "POST",
  "mode": "cors",
  "credentials": "include"
});`

and JS code

`await sp.web.lists.getByTitle(list_title).items.getById(id).update({
                        [field_name]: {
                            "__metadata": { "type": "SP.FieldUrlValue" },
                            "Description": file.fileNameWithoutExtension,
                            "Url": file.fileAbsoluteUrl
                        },
                        "__metadata":{"type":"SP.ListItem"}
                    });`

I did noticed that the request header content-type is sending as "application/json". When I tried to re-send the fetch code manually in dev tools, and changed that header to "application/json;odata=verbose" it did work. Maybe there is a bug and it is not sending this on POST commands?

**Comment by patrick-rodgers** [comment]
That looks like a bug, we'll have a look. Thanks for letting us know.

**Comment by tavikukko** [comment]
__metadata not needed, try this.
```typescript
await sp.web.lists.getByTitle(list_title).items.getById(id).update({
    "Description": file.fileNameWithoutExtension,
    "Url": file.fileAbsoluteUrl
  },
);
```

**Comment by antoniocguillen** [comment]
It worked.

Thanks for your help.
