### ISSUE TITLE
Node project using TypeScript producing commonjs modules

### ISSUE THREAD

**Issue by necik11** [pnp/pnpjs#2211]
### Category
- [ ] Enhancement
- [ ] Bug
- [x ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [3.2.0]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question
I was trying use PnP in Power Apps component framework (React app).

I use :
```
pac pcf init --namespace xxxx --name xxxx --template field
npm install
```

This generate react/typescript solution.
And then I wanna just add PnP connect to index.ts, but I can't achieve that.

I tried go step by step by documentation:
https://pnp.github.io/pnpjs/getting-started/#getting-started-with-nodejs

so:
1. ```npm i @pnp/sp @pnp/nodejs```
and then import function() {} from tutorial.
But i got many errors, ending:
```
ERROR in node:zlib
Module build failed: UnhandledSchemeError: Reading from "node:zlib" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
    at C:\React_Learning\3_PCF_PnP\node_modules\webpack\lib\NormalModule.js:832:25
    at Hook.eval [as callAsync] (eval at create (C:\React_Learning\3_PCF_PnP\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Object.processResource (C:\React_Learning\3_PCF_PnP\node_modules\webpack\lib\NormalModule.js:829:8)
    at processResource (C:\React_Learning\3_PCF_PnP\node_modules\loader-runner\lib\LoaderRunner.js:220:11)
    at iteratePitchingLoaders (C:\React_Learning\3_PCF_PnP\node_modules\loader-runner\lib\LoaderRunner.js:171:10)
    at runLoaders (C:\React_Learning\3_PCF_PnP\node_modules\loader-runner\lib\LoaderRunner.js:398:2)
    at NormalModule._doBuild (C:\React_Learning\3_PCF_PnP\node_modules\webpack\lib\NormalModule.js:819:3)
    at NormalModule.build (C:\React_Learning\3_PCF_PnP\node_modules\webpack\lib\NormalModule.js:963:15)
    at C:\React_Learning\3_PCF_PnP\node_modules\webpack\lib\Compilation.js:1371:12
    at NormalModule.needBuild (C:\React_Learning\3_PCF_PnP\node_modules\webpack\lib\NormalModule.js:1253:32)
 @ ./node_modules/node-fetch/src/index.js 14:0-29 302:17-34 303:23-40 307:28-45 329:32-50 335:32-53 358:28-55
 @ ./node_modules/@pnp/nodejs/index.js 1:0-40 6:16-33 10:16-33 14:17-35
 @ ./pnpControl/index.ts 155:15-37

10 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.72.0 compiled with 22 errors and 1 warning in 5069 ms
[pcf-scripts] [Error] encountered unexpected error:
Error: An error occurred compiling or bundling the control.
```
I tried either too:
https://pnp.github.io/pnpjs/getting-started/#using-pnpgraph-graphfi-factory-interface-in-nodejs
But same error.

Then i noticed i am using typescript project and for TS its some else:
https://pnp.github.io/pnpjs/getting-started/#node-project-using-typescript-producing-commonjs-modules

but when i use these two rows in **tsconfig.json**:
```
{
    "compilerOptions": {
        "module": "CommonJS",
        "moduleResolution": "node12"
}
```
i will get this error:
Compiler option 'moduleResolution' of value 'node12' is unstable. Use nightly TypeScript to silence this error. Try updating with 'npm install -D typescript@next'
Of course i was trying :

'npm install -D typescript@next'¨

either another version TS for sample from your sample project:
https://github.com/pnp/pnpjs/blob/version-3/samples/nodejs-commonjs/tsconfig.json
but same error.

I am using VS code. Already tried change local version of TS not help.

Either i tried:
https://github.com/pnp/pnpjs/tree/f724231148c4b221acb190c11d1795934dab7719/samples/nodejs-app

where is in tsconfig.json these 2 rows:
```
   "module": "ESNext",
    "moduleResolution": "node"
```        
which tsconfig.json stop show error, but after npm run build again errors show.

For a while, it looked promising with this setting, which is not in the Documentation.
But if I use this setting, I'll still get errory build again.

From the documentation:
Finally, when launching node you need to include the `` flag with a setting of 'node'.
node --experimental-specifier-resolution=node dist/index.js

But i don't have any dist folder here, so i have if I set in tsconfig.json:
     "outDir": "./dist",

But pcf app is generated in another folder not root.there is how its looks:

![picture1](https://i.ibb.co/q0CwnX2/pcf-pnp.png)

There is: **package.json**:
```
{
  "name": "pcf-project",
  "version": "1.0.0",
  "description": "Project containing your PowerApps Component Framework (PCF) control.",
  "scripts": {
    "build": "pcf-scripts build",
    "clean": "pcf-scripts clean",
    "rebuild": "pcf-scripts rebuild",
    "start": "pcf-scripts start",
    "refreshTypes": "pcf-scripts refreshTypes"
  },
  "dependencies": {
    "@pnp/graph": "^3.2.0",
    "@pnp/nodejs": "^3.2.0",
    "@pnp/sp": "^3.2.0"
  },
  "devDependencies": {
    "@types/node": "^16.4",
    "@types/powerapps-component-framework": "^1.3.0",
    "@typescript-eslint/eslint-plugin": "^4.29.0",
    "@typescript-eslint/parser": "^4.29.0",
    "eslint": "^7.32.0",
    "eslint-plugin-import": "^2.23.4",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^5.1.0",
    "pcf-scripts": "^1",
    "pcf-start": "^1",
    "typescript": "^4.3"
  }
}
```

I already founded more ppl which asking for it:

https://powerusers.microsoft.com/t5/Building-Power-Apps/Fetching-data-from-SharePoint-list-using-PnP-JS-in-PowerApps/td-p/856908

Maybe i am doing it wrong and i can't use pnp / js v3 and do i need to go back to v2?

"Version 3 of this library only supports ESModules. If you still require commonjs modules please check out version 2."

### Observed Behavior
Connect to SHP Online from React control.

**Comment by patrick-rodgers** [comment]
I'll be honest, this isn't a scenario I've ever tried. Give us some time to research it and we'll see what we can come up with. Thanks for the detailed information, will def help - and bringing up this use case, good for us to do our best to support it. Thanks!

**Comment by juliemturner** [comment]
So I got this working in a local harness, but I think it's going to really depend on where you're trying to use the component with regards to PowerApps hosting... 

Essentially I installed the @pnp/sp and @pnp/msaljsclient packages and then I used the [MSAL + SP + Browser](https://pnp.github.io/pnpjs/concepts/authentication/#msal-sp-browser) auth example to create the sp object in the initialization of the control and then used that to get data. In my sample that was the WebInfo object for a web that I hard coded the path to, but could probably have been passed as a property to the control.

![image](https://user-images.githubusercontent.com/7570936/170100456-0a8b46b0-3561-4ac9-873a-a5fda05f733c.png)

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
