### ISSUE TITLE
file.addChunked does not support streams

### ISSUE THREAD

**Issue by wmertens** [pnp/pnpjs#2214]
### Category
- Bug

### Version

Please specify what version of the library you are using: [     v3    ]

Please specify what version(s) of SharePoint you are targeting: [  online       ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question

[The documentation](https://pnp.github.io/pnpjs/sp/files/#adding-a-file-using-nodejs-streams) says to use addChunked when uploading streams.

However, this is not actually working, it ends up calling File.setContentChunked which only accepts blobs.

Sidenote: If file is not defined, [this will crash](https://github.com/pnp/pnpjs/blob/36040c64341c50fe95cfb2fad112620da5a66e89/packages/sp/files/types.ts#L388) on file.length. Plus `file` is required so the ?. is not really needed for the Blob case.

**Comment by wmertens** [comment]
Sure:
```js
                // const folder = ...IFolder gotten from pnp
                const stream = fs.createReadStream(fromPath)
	
		const {data} = await folder.files.addChunked(
			name,
			stream,
			undefined, // progress function
			true // overwriting the previous version
		)
```

This results in 

```
    upload failed TypeError: file.slice is not a function
        at Proxy.setContentChunked (/home/wmertens/Projects/StratoSync/node_modules/.pnpm/@pnp+sp@3.1.0/packages/sp/files/types.ts:394:74)
        at Proxy.addChunked (/home/wmertens/Projects/StratoSync/node_modules/.pnpm/@pnp+sp@3.1.0/packages/sp/files/types.ts:86:27)
[...]
```

**Comment by wmertens** [comment]
😳 oh wow I totally missed that, I didn't expect there to be imports with side-effects. Now it works indeed, but I wonder how I would have noticed it.

Maybe the docs should add a comment like `// Required for NodeJS support` before the import? Still not sure I would have seen it, I generally don't pay much attention to the imports section.

And yes, I did read the documentation :smile:. Maybe a separate subsection at the start of https://pnp.github.io/pnpjs/getting-started/#getting-started-with-nodejs drawing attention to this import would have helped me. Do you think we can add that?
