### ISSUE TITLE
Trying to add item to a list, list.items always undefined

### ISSUE THREAD

**Issue by BlueBird67** [pnp/pnpjs#2303]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: 
- "typescript": "~4.2.4"
- Node version : 14.15.5
- @microsoft/rush-stack-compiler-4.2": "^0.1.2"
- "@pnp/sp": "^3.3.2"
- "@microsoft/sp-core-library": "1.14.0"
- "@microsoft/sp-lodash-subset": "1.14.0"
- "@microsoft/sp-office-ui-fabric-core": "1.14.0"
- "@microsoft/sp-property-pane": "1.14.0"
 - "@microsoft/sp-webpart-base": "1.14.0"

Please specify what version(s) of SharePoint you are targeting: **Latest SharePoint Online**

### Expected / Desired Behavior / Question
Directly in OnInit() of my FormWebPart.ts
`const sp:SPFI = spfi().using(SPFx(this.context));`
`await this._sp.web.lists.getByTitle(listName).items.add(item).then((iar: IItemAddResult) => {
    resolve(iar);
});`

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'add')
at ListService.<anonymous> (SharePointService.ts:55:64)
at step (onboarding-form-web-part.js:79396:23)
at Object.next (onboarding-form-web-part.js:79377:53)
at fulfilled (onboarding-form-web-part.js:79368:58)`

My context is good, I checked by debug. 
Lists have the correct web rest call, and contain all the lists of the web site.
`this._sp.web.lists.getByTitle(listName)` get the correct list with correct information.

But items is undefined, always... Test is only on workbench for the moment.

I've tested on 2 different tenants, same result.

**Comment by BlueBird67** [comment]
So it's solved. I missed the 
`import "@pnp/sp/items";`
import... 

Wasn't aware it was mandatory.
