### ISSUE TITLE
Node v18 SharePoint File Download Error

### ISSUE THREAD

**Issue by TylerSmart** [pnp/pnpjs#2461]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

|Library|Version|
|-|-|
|@azure/msal-node|1.14.2|
|@pnp/nodejs-commonjs|2.14.0|
|SharePoint|SharePoint in Microsoft 365|
|Node.js|18.12.0|

*Please note that this error does not occur when using Node v17 or v16*

### Expected / Desired Behavior / Question
The code should download a blob for the specified XLSX file within SharePoint.

### Steps to Reproduce
- Node should be running on v18.*.* and a file should be uploaded to SharePoint.
- Configure the `sp.setup`, adjusting the key, thumbprint, IDs, and URLs as necessary:
```javascript
sp.setup({
	sp: {
		baseUrl: 'BASE_URL',
		fetchClientFactory: () => {
			return new MsalFetchClient(
				{
					auth: {
						authority:
							'AUTH_URL',
						clientCertificate: {
							thumbprint: 'THUMBPRINT',
							privateKey: 'PRIVATE_KEY',
						},
						clientId: 'CLIENT_ID',
					},
				},
				['URL'],
			);
		},
	},
});
```
- Run the following code, adjusting the relative path and name as needed:
```javascript
const blob = await sp.web
	.getFolderByServerRelativePath('DIRECTORY_PATH')
	.files.getByName('FILE_NAME')
	.getBlob();
```

- Observe the following error output:
```
TypeError: Failed to parse URL from 
    at new Request (node:internal/deps/undici/undici:9474:19)
    at mergeHeaders (C:\Users\...\packages\common\net.ts:33:22)
    ... 10 lines matching cause stack trace ...
    at descriptor.value (C:\Users\...\packages\odata\pipeline.ts:105:27)
    at next (C:\Users\...\packages\odata\pipeline.ts:56:48)
    at C:\Users\...\packages\odata\pipeline.ts:105:83
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:393:5)
      at URL.onParseError (node:internal/url:565:9)
      at new URL (node:internal/url:645:5)
      at new Request (node:internal/deps/undici/undici:9472:25)
      at mergeHeaders (C:\Users\...\packages\common\net.ts:33:22)
      at SPHttpClient.<anonymous> (C:\Users\...\packages\sp\sphttpclient.ts:50:21)
      at step (C:\Users\...\server\node_modules\tslib\tslib.js:143:27)
      at Object.next (C:\Users\...\server\node_modules\tslib\tslib.js:124:57)
      at C:\Users\...\server\node_modules\tslib\tslib.js:117:75
      at new Promise (<anonymous>)
      at __awaiter (C:\Users\...\server\node_modules\tslib\tslib.js:113:16)
      at SPHttpClient.fetch (C:\Users\...\server\node_modules\@pnp\sp-commonjs\sphttpclient.js:28:38)
      at C:\Users\...\packages\odata\pipeline.ts:216:24
      at new Promise (<anonymous>)
      at Function.PipelineMethods.send (C:\Users\...\packages\odata\pipeline.ts:193:16)      
      at descriptor.value (C:\Users\...\packages\odata\pipeline.ts:105:27) {
    input: '',
    code: 'ERR_INVALID_URL'
  }
}
```

**Comment by juliemturner** [comment]
V2 doesn't support this version of NodeJS...
Is there a reason you aren't using V3?

**Comment by patrick-rodgers** [comment]
FWIW this appears to work in node 18 with v3. Our current target is node 16, though I am unaware of anything we use that would break between versions (famous last words)

**Comment by TylerSmart** [comment]
> V2 doesn't support this version of NodeJS... Is there a reason you aren't using V3?

No, I must have overlooked the fact that there was a V3 since it got moved to a different NPM package.

> FWIW this appears to work in node 18 with v3. Our current target is node 16, though I am unaware of anything we use that would break between versions (famous last words)

I can also confirm that this works after upgrading the system to V3 using Node v18.

Given those developments, it isn't necessary for me that V2 support this anymore.

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
