### ISSUE TITLE
Error handling (maybe only related to `sp.utility.sendEmail`) in AzureFunction

### ISSUE THREAD

**Issue by trueleader** [pnp/pnpjs#2564]
### Category
- ? Bug
- Question

### Version
- Please specify what version of the library you are using: 3.11
- Please specify what version(s) of SharePoint you are targeting: SPO

### Expected / Desired Behavior / Question
Continue using code/library after error (maybe only related to `sp.utility.sendEmail`)

### Observed Behavior
Azure Function NodeJS server crashes and restarts on next MicroTask after:
```typescript
	try
	{
		await sp.utility.sendEmail({
			To: ["someInvalidForSp@test.com"],
			Subject: "Test Subject",
			Body: "Test Body"
		});
	}
	catch (e)
	{
		console.log("Broken: catched email error which we don´t interested in");
	}
```

Don´t know if the problem is initiated by pnpjs or a bug in azure function.
```
PS C:\Projects\Custom\TestAzureFunc\testFunc> npm run build

> broken_email_sample@1.0.0 build
> tsc

PS C:\Projects\Custom\TestAzureFunc\testFunc> func start

Azure Functions Core Tools
.js:45:15)     at async Timeout._onTimeout (file:///C:/Projects/Custom/TestAzureFunc/testFunc/node_modules/@pnp/queryable/queryable.js:120:50)
[2023-02-10T16:49:17.253Z] Language Worker Process exited. Pid=28496.
[2023-02-10T16:49:17.254Z] node exited with code 1 (0x1). LanguageWorkerConsoleLog[error] Worker a94f124d-a10d-4bf7-b8f5-7de34c1f0d51 uncaught exception (learn more: https://go.microsoft.com/fwlink/?linkid=2097909 ): Error: Error making HttpClient request in queryable [400] Bad Request ::> {"odata.error":{"code":"-2130242040, Microsoft.SharePoint.SPException","message":{"lang":"en-US","value":"Die E-Mail-Nachricht kann nicht gesendet werden. Stellen Sie sicher, dass die E-Mail-Nachricht einen g\u00fcltigen Empf\u00e4nger aufweist."}}}     at Function.init (file:///C:/Projects/Custom/TestAzureFunc/testFunc/node_modules/@pnp/queryable/behaviors/parsers.js:96:16)     at processTicksAndRejections (node:internal/process/task_queues:96:5)     at async Proxy.errorCheck (file:///C:/Projects/Custom/TestAzureFunc/testFunc/node_modules/@pnp/queryable/behaviors/parsers.js:45:15)     at async Timeout._onTimeout (file:///C:/Projects/Custom/TestAzureFunc/testFunc/node_modules/@pnp/queryable/queryable.js:120:50).
[2023-02-10T16:49:17.311Z] Executed 'Functions.HttpTrigger1' (Failed, Id=b13044af-8a66-4d71-885d-a1461fa2e5ed, Duration=2381ms)
[2023-02-10T16:49:17.313Z] System.Private.CoreLib: Exception while executing function: Functions.HttpTrigger1. System.Private.CoreLib: node exited with code 1 (0x1). LanguageWorkerConsoleLog[error] Worker a94f124d-a10d-4bf7-b8f5-7de34c1f0d51 uncaught exception (learn more: https://go.microsoft.com/fwlink/?linkid=2097909 ): Error: Error making HttpClient 
request in queryable [400] Bad Request ::> {"odata.error":{"code":"-2130242040, Microsoft.SharePoint.SPException","message":{"lang":"en-US","value":"Die E-Mail-Nachricht kann nicht gesendet werden. Stellen Sie sicher, dass die E-Mail-Nachricht einen g\u00fcltigen Empf\u00e4nger aufweist."}}}     at Function.init (file:///C:/Projects/Custom/TestAzureFunc/testFunc/node_modules/@pnp/queryable/behaviors/parsers.js:96:16)     at processTicksAndRejections (node:internal/process/task_queues:96:5)     at async Proxy.errorCheck (file:///C:/Projects/Custom/TestAzureFunc/testFunc/node_modules/@pnp/queryable/behaviors/parsers.js:45:15)     at async Timeout._onTimeout (file:///C:/Projects/Custom/TestAzureFunc/testFunc/node_modules/@pnp/queryable/queryable.js:120:50).
[2023-02-10T16:49:17.710Z] Worker process started and initialized.
```

![image](https://user-images.githubusercontent.com/7026107/218149465-da3775d4-29da-4e57-a603-292bdbae5bb2.png)

### Steps to Reproduce
Created sample test Azure Function Project: 
[testFunc.zip](https://github.com/pnp/pnpjs/files/10709576/testFunc.zip)

HttpTrigger1 contains the test-function. `buildDefaultSpTimeline` is a copy of SPDefault code but replaces the MSAL auth by DefaultAzureCredential.

- requires local [Azure Functions Core Tools](https://learn.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=v4%2Cwindows%2Ccsharp%2Cportal%2Cbash#v2) installed
- requires SPO site
- requires user is logged in locally (e.g. via Azure CLI)

- open terminal in extracted folder
- install node_modules: npm i
- build project: npm run build
- start azure function: func start
- open the http-triggered function via browser: http://localhost:7071/api/HttpTrigger1

**Comment by patrick-rodgers** [comment]
Not sure I follow, the error when I translate is: "The e-mail message cannot be sent. Make sure that the e-mail message has a valid recipient."

You could try 3.12 just released today as it [has a fix](https://github.com/pnp/pnpjs/pull/2540) that might be related and let us know if that resolves this.

**Comment by trueleader** [comment]
3.12 is working correct, thank you :)

The problem occured inside a large process, I only stripped it down to this example. The addresses are correct but may be declined by SPO because of "external" restrictions. I catch and handle the error, which didn´t work before, because the server crashed :)
