### ISSUE TITLE
Error in batch when adding fields to list

### ISSUE THREAD

**Issue by JackStrap** [pnp/pnpjs#2646]
### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [x] Documentation gap/issue

### Version

Please specify what version of the library you are using:  
- SPFx: ^1.61.1 - 1.17.1  
- PnPjs: 3.14.0  

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question
I'm adding fields to a list with batch and i'm getting errors 409 in almost all of the catch in the added fields.  
But all the fields are added to the list.

I tried both ways to do the batch, createBatch and using a batched web.

### Observed Behavior
Error in console.
```JavaScript
Error: Error making HttpClient request in queryable [409]  ::> {"odata.error":{"code":"-2130575305, Microsoft.SharePoint.SPException","message":{"lang":"en-US","value":"Save Conflict.\n\nYour changes conflict with those made concurrently by another user. If you want your changes to be applied, click Back in your Web browser, refresh the page, and resubmit your changes."}}}
  at HttpRequestError.init (parsers.js:96:1)
  at async Proxy.errorCheck (parsers.js:45:1)
  at async queryable.js:120:1
 ```

### Steps to Reproduce
```TypeScript
import { stringIsNullOrEmpty } from '@pnp/core/util';

import { SPFI } from '@pnp/sp';
import "@pnp/sp/batching";
import { createBatch } from '@pnp/sp/batching';
import "@pnp/sp/fields/list";
import "@pnp/sp/items";
import "@pnp/sp/lists";
import "@pnp/sp/views/list";
import "@pnp/sp/webs";

// I get the 'this.spFI' in the constructor
// this.spFI = getSP();

const [batchedSP, execute] = this.spFI.web.batched();
const listClient = batchedSP.lists.getByTitle(listName);

// const listClient = this.spFI.web.lists.getByTitle(listName);
// const [batchedListBehavior, execute] = createBatch(listClient);
// listClient.using(batchedListBehavior);

listClient.fields.addText("clientHome", { MaxLength: 255, Group: listName }).then(r => console.log(r)).catch(e => console.log('catch', e));

// Add all products to list
for (const product of allProducts) {

  if (!stringIsNullOrEmpty(product.Code)) {
    listClient.fields.addNumber(product.Code, { MinimumValue: 1, MaximumValue: 9999999999, Group: listName })
    .then().catch(e => console.log('catch', e));
  }

}

await execute();
```

Thank you in advance!

**Comment by juliemturner** [comment]
Try changing you loop to a 
`for(let p=0; p<allProducts.length; p++)`
and see if that helps.

I cannot remember if there's a limitation on creating fields in a batch or not.... I feel like there's a question about this already that was closed, might try searching the issue list.

**Comment by JackStrap** [comment]
Hi thanks for the fast comeback.

I changed my loop and i got the same result.
![image](https://user-images.githubusercontent.com/21227974/233184465-2cd502e2-d2ac-4a3f-a80c-f6eaa4d0f017.png)


yes i already check the issue list, i see that their is two issue closed related to batch.
[https://github.com/pnp/pnpjs/issues/2579](https://github.com/pnp/pnpjs/issues/2579)
[https://github.com/pnp/pnpjs/issues/2597](https://github.com/pnp/pnpjs/issues/2597)

**Comment by juliemturner** [comment]
Something about your code isn't right, you shouldn't see multiple posts that's the whole point a batched call issues one call with a payload for each of the entries... I'm not really seeing the issue but maybe try  decoupling the const you created for listClient. In other words don't use that constant spell it out for the two calls.

**Comment by bcameron1231** [comment]
Just wanted to provide a quick update to this, I'm actively looking into this. There may be an issue with how we are handling the addition of fields which may not be compatible with batching.

**Comment by JackStrap** [comment]
Ok, i changed my code like this, but i'm getting the same result.
But like i said all the fields are added to list and i can work with them after. 

```TypeScript
const [batchedSP, execute] = this.spFI.web.batched();
const listClient = batchedSP.lists.getByTitle(listName);

batchedSP.lists.getByTitle(listName).fields.addText("clientHome", { MaxLength: 255, Group: listName }).then(r => console.log(r)).catch(e => console.log('catch', e));

// Add all products to list
for (let p=0; p<allProducts.lenght; p++) {

  if (!stringIsNullOrEmpty(allProducts[p].Code)) {
    batchedSP.lists.getByTitle(listName).fields.addNumber(allProducts[p].Code, { MinimumValue: 1, MaximumValue: 9999999999, Group: listName })
    .then().catch(e => console.log('catch', e));
  }

}

await execute();
```

I don't know if that could help but here's the full error i get in the console. 

```JavaScript
POST https://xxx.sharepoint.com/sites/DEV_SB/_api/web/lists/getByTitle('LoterieTP230420131808Clients')/fields('ce02327b-3b7a-493f-92ac-f7ee5e8d0812') 409
retry @ browser-fetch.js:61
(anonymous) @ browser-fetch.js:83
(anonymous) @ moments.js:68
(anonymous) @ timeline.js:151
(anonymous) @ queryable.js:117
setTimeout (async)
execute @ queryable.js:88
start @ timeline.js:183
post @ operations.js:8
op @ operations.js:20
spPost @ operations.js:5
spPostMerge @ operations.js:9
update @ types.js:283
await in update (async)
add @ types.js:60
await in add (async)
addNumber @ types.js:132
LotterySheet.createClientList @ LotterySheet.tsx:378
await in LotterySheet.createClientList (async)
LotterySheet.lotteryAdd @ LotterySheet.tsx:278
await in LotterySheet.lotteryAdd (async)
LotterySheet.validateForm @ LotterySheet.tsx:209
Ve @ sp-pages-assembly_en-us_380255c8e20811346b873b876a9bc242.js:69
Qe @ sp-pages-assembly_en-us_380255c8e20811346b873b876a9bc242.js:69
(anonymous) @ sp-pages-assembly_en-us_380255c8e20811346b873b876a9bc242.js:69
wa @ sp-pages-assembly_en-us_380255c8e20811346b873b876a9bc242.js:69
Ea @ sp-pages-assembly_en-us_380255c8e20811346b873b876a9bc242.js:69
(anonymous) @ sp-pages-assembly_en-us_380255c8e20811346b873b876a9bc242.js:69
Ue @ sp-pages-assembly_en-us_380255c8e20811346b873b876a9bc242.js:69
(anonymous) @ sp-pages-assembly_en-us_380255c8e20811346b873b876a9bc242.js:69
Ta @ sp-pages-assembly_en-us_380255c8e20811346b873b876a9bc242.js:69
Zt @ sp-pages-assembly_en-us_380255c8e20811346b873b876a9bc242.js:69
Xt @ sp-pages-assembly_en-us_380255c8e20811346b873b876a9bc242.js:69
IKDZ.t.unstable_runWithPriority @ sp-pages-assembly_en-us_380255c8e20811346b873b876a9bc242.js:69
Ki @ sp-pages-assembly_en-us_380255c8e20811346b873b876a9bc242.js:69
Pe @ sp-pages-assembly_en-us_380255c8e20811346b873b876a9bc242.js:69
Yt @ sp-pages-assembly_en-us_380255c8e20811346b873b876a9bc242.js:69
```

Thanks.

**Comment by bcameron1231** [comment]
Thanks for this.  We indeed have a problem with our batching in regard to fields, so for the time being you'll have to do your field additions. We're discussing internally on the best way to fix this.

**Comment by bcameron1231** [comment]
Quick update, we're working on a fix for this.

**Comment by JackStrap** [comment]
Thanks!
