### ISSUE TITLE
ERROR: Cannot read properties of undefined (reading '__extends')

### ISSUE THREAD

**Issue by Couta7** [pnp/pnpjs#2672]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: v1.2.1
Please specify what version(s) of SharePoint you are targeting: SPO

### Observed Behavior

```Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
ERROR:
Cannot read properties of undefined (reading '__extends')

CALL STACK:
TypeError: Cannot read properties of undefined (reading '__extends')
    at https://unpkg.com/@pnp/odata@1.2.1/dist/odata.es5.umd.min.js:10:2144
    at Object.<anonymous> (https://unpkg.com/@pnp/odata@1.2.1/dist/odata.es5.umd.min.js:10:2161)
    at Object.execCb (eval at e (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_d175a450223b4f83b4f34272c36ea32b.js:70:747975), <anonymous>:30:41)
    at Z.check (eval at e (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_d175a450223b4f83b4f34272c36ea32b.js:70:747975), <anonymous>:18:439)
    at Z.enable (eval at e (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_d175a450223b4f83b4f34272c36ea32b.js:70:747975), <anonymous>:23:439)
    at Z.init (eval at e (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_d175a450223b4f83b4f34272c36ea32b.js:70:747975), <anonymous>:17:108)
    at E (eval at e (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_d175a450223b4f83b4f34272c36ea32b.js:70:747975), <anonymous>:14:221)
    at Object.completeLoad (eval at e (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_d175a450223b4f83b4f34272c36ea32b.js:70:747975), <anonymous>:28:337)
    at HTMLScriptElement.onScriptLoad (eval at e (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_d175a450223b4f83b4f34272c36ea32b.js:70:747975), <anonymous>:30:166)
````

Since this week the sharepoint webpart it's not working

**Comment by juliemturner** [comment]
Version 1 of this library has long been out of support.

That said I don't really have enough information to go on to take a guess at what your issue might be. If you can provide more information about what code is running that is causing this error we might be able to provide some guidance.

**Comment by bcameron1231** [comment]
Typically, I've seen this because of a typescript compiler error. That is, the version of typescript used isn't compatible with the one being transpiled. As Julie mentioned, you're using a really old version of PnPjs. I would recommend upgrading to the latest verison.

**Comment by patrick-rodgers** [comment]
I want to set expectations here, we aren't going to release any updates to v1. As well it appears that you are using one of the premade bundles we used to release "odata.es5.umd.min.js" so likely others. Those haven't changed since release - so I would say back to you "nothing has changed and never had problems before", what has changed on your end?

The best path here would be to update to v3 of the library, which hopefully won't be too bad, and it sounds like you have access to the source. But if this was written in SPFx 5 years ago it is probably time to update the whole thing.

**Comment by bcameron1231** [comment]
Closing this issue as answered. The v1 package hasn't changed in many years, and the issues seem to be because of environment changes (possibly in SPO). We also have no plans to update for make any fixes to V1. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
