### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'prototype')

### ISSUE THREAD

**Issue by viceice** [pnp/pnpjs#2681]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: 3.15.0

Please specify what version(s) of SharePoint you are targeting: Online

### Expected / Desired Behavior / Question
Updating from v3.14.0 to v3.15.0 should not break the build.

### Observed Behavior
Test are failing with `TypeError: Cannot read properties of undefined (reading 'prototype')`

```
FAIL libs/sp/common/src/lib/common.module.spec.ts
  ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'prototype')

    > 1 | import '@pnp/sp/sites';
        | ^
      2 | import '@pnp/sp/webs';
      3 | import '@pnp/sp/lists';
      4 | import '@pnp/sp/files';

      at Object.<anonymous> (../../node_modules/@pnp/sp/batching.js:13:6)
      at Object.<anonymous> (../../node_modules/@pnp/sp/behaviors/request-digest.js:6:1)
      at Object.<anonymous> (../../node_modules/@pnp/sp/index.js:13:1)
      at Object.<anonymous> (../../node_modules/@pnp/sp/webs/types.js:7:1)
      at Object.<anonymous> (../../node_modules/@pnp/sp/sites/types.js:4:1)
      at Object.<anonymous> (../../node_modules/@pnp/sp/sites/index.js:2:1)
      at Object.require (pnp/src/lib/pnp-imports.ts:1:1)
      at Object.require (pnp/src/lib/pnp.service.ts:1:1)
      at Object.require (pnp/src/public_api.ts:2:1)
      at Object.require (pnp/src/index.ts:2:1)
      at Object.require (common/src/lib/services/action/sp-permission.service.ts:21:1)
      at Object.require (common/src/lib/common.module.ts:4:1)
      at Object.<anonymous> (common/src/lib/common.module.spec.ts:2:1)
```

### Steps to Reproduce
I'm using a `nx` workspace with an angular library where i import the following pnpjs libs:

```ts
import '@pnp/sp/sites';
import '@pnp/sp/webs';
import '@pnp/sp/lists';
import '@pnp/sp/files';
import '@pnp/sp/folders';
import '@pnp/sp/fields/web';
import '@pnp/sp/fields/list';
import '@pnp/sp/items/list';
import '@pnp/sp/site-users/web';
import '@pnp/sp/profiles';
import '@pnp/sp/content-types/list';
import '@pnp/sp/content-types/web';
```
Testes are executed as `commonjs` from `typescript` with `jest` and `ts-jest` under the hood.

Let me know if further details are required

**Comment by viceice** [comment]
![image](https://github.com/pnp/pnpjs/assets/1798109/9221d43f-a7b2-46d6-a466-3f7bf7a0fe22)

https://github.com/pnp/pnpjs/blob/5a867ddd19d0360ad6f433220f96241cc2635c8b/packages/sp/batching.ts#L41

**Comment by viceice** [comment]
It's a circular reference. `extractWebUrl` should be imported from `../utils/extract-web-url.js` instead of `../index.js`

https://github.com/pnp/pnpjs/blob/5a867ddd19d0360ad6f433220f96241cc2635c8b/packages/sp/webs/types.ts#L19
