### ISSUE TITLE
Add file -> 403 access denied

### ISSUE THREAD

**Issue by tor-axbit** [pnp/pnpjs#2694]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  
"@pnp/graph": "^3.14.0",
    "@pnp/logging": "^3.14.0",
    "@pnp/nodejs": "^3.14.0",
    "@pnp/sp": "^3.14.0"
]

Please specify what version(s) of SharePoint you are targeting: [ SP Online]

### Question
This procedure should create a PDF file from a blob, and add to a specific folder. All PnP methods was recently upgraded from version 2 to 3. All PnP methods in the application works, except for this file adding one. Am I overseeing some really basic stuff, or is this something else?

Here is a snippet of the working version, before upgrade to PnP 3. If the user was granted `Edit` permission in SPO, this worked as expected. A PDF File is created from the `blob`, and added to the correct folder. 
```
import { Web } from "@pnp/sp/webs";

....
  const pdfDocGenerator = pdf.createPdf(finalDocDefinition);
  pdfDocGenerator.getBlob(async (blob) => {
   
   // Gets relative Url like "sites/SUBSITE/
    const workspaceSubsiteUrl = await Helper.getWorkspaceSubsiteRelativeUrl(
      props.id
    );

    const targetWeb = Web(
      "https://ORG.sharepoint.com" + workspaceSubsiteUrl
    );

    const targetFolder = `${workspaceSubsiteUrl}${props.id}`;
    const temp = await targetWeb.getFolderByServerRelativeUrl(targetFolder);

    temp.files.add(`${props.name}.pdf`, blob, true).then(() => {
      props.showModal(false);
      window.open(targetFolder, "_blank");
    });
  });

....
```

### Observed Behavior
This is the error message
```
Uncaught (in promise) Error: Error making HttpClient request in queryable [403]  ::> 
{"odata.error":{"code":"-2147024891, System.UnauthorizedAccessException",
"message":{"lang":"en-US","value":"Access denied."}}}
    at HttpRequestError.init (parsers.js:96:1)
    at async Proxy.errorCheck (parsers.js:45:1)
    at async queryable.js:120:1
init @ parsers.js:96
```

This is the refactored version of the procedure. 
```
const _sp = getSP(context);

(snip)

pdfDocGenerator.getBlob(async (blob) => {
  const workspaceSubsiteUrl = await getWorkspaceSubsiteRelativeUrl(
    props.id,
    context
  );

  const targetWeb = Web([
    _sp.web,
    "https://TENANT.sharepoint.com/sites/SUBSITE",
  ]);

  const targetFolder = `${workspaceSubsiteUrl}${props.id}`;

  const temp = await targetWeb.getFolderByServerRelativePath(
    targetFolder
  );

  temp.files
    .addUsingPath(`${props.name}.pdf`, blob, { Overwrite: true })
    .then(() => {
      window.open(targetFolder, "_blank");
      console.log("File uploaded successfully");
      props.showModal(false);
    });
});
```
It seems like the refactored procedure gets the correct subsite, and the correct folder. I set a breakpoint at the `temp` variable, and copy-paste the link found in `[target]` of the instance, into a browser. That link produces an XML response which I can not reproduce here, but a small snippet:

```
<content type="application/xml">
    <m:properties>
        <d:Exists m:type="Edm.Boolean">true</d:Exists>
(snip)
    </m:properties>
</content>
```

In the same application, using `copyByPath` to copy documents from another SPO subsite to the same folder works as expected. 

```
for (const doc of documents) {
    const file = await TARGETWeb.getFileByUrl(doc.url);
    const item = await file.getItem<{ Title: string }>("Title");

    const fileName = doc.fileName

    const workspaceSubsiteUrl = await getWorkspaceSubsiteRelativeUrl(
      props.id,
      context
    );

    const targetFolder = `${workspaceSubsiteUrl}${props.id}`;
    let destinationUrl = `${targetFolder}/${DocFolderName}/${fileName}`;

    await file.copyByPath(destinationUrl, false, true);
  }
```

**Comment by tor-axbit** [comment]
I solved the problem by using `folderFromAbsolutePath` instead. The problem might have been a peculiar naming of the subsite document folder, not sure.

```
folderFromAbsolutePath(_sp.web, absoluteUrlComplete).then((folder) => {
  folder.files
    .addUsingPath(encodedPDFName, blob, { Overwrite: true })
    .then((r) => {
      window.open(targetFolder, "_blank");
      console.log("File uploaded successfully");
      props.showModal(false);
    });
});
```
