### ISSUE TITLE
NodeJS + MSAL = window is not defined?

### ISSUE THREAD

**Issue by axelvugts** [pnp/pnpjs#2709]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [x] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 3.15.0 ]

Please specify what version(s) of SharePoint you are targeting: [ SharePoint Online ]

### Question
I'm trying to download and upload some files from/to SharePoint Online in a NodeJS project, using v3 of pnp/sp. However, I can't get MSAL-authentication to work. Whenever I try to create the MSAL-configuration, the application throws an error.
What am I missing here?

### Observed Behavior
My code throws the following error on the line where msalConfig is set:
```
ReferenceError: window is not defined
    at AuthCache.BrowserStorage (~/project/node_modules/msal/lib-commonjs/cache/BrowserStorage.js:15:9)
    at new AuthCache (~/project/node_modules/msal/lib-commonjs/cache/AuthCache.js:22:28)
    at new UserAgentApplication (~/project/node_modules/msal/lib-commonjs/UserAgentApplication.js:84:29)
    at MSAL (file://~/project/node_modules/@pnp/msaljsclient/index.js:3:17)
    at forwardCall (file://~/project/app/controllers/coolController.js:78:28)
    at dispatch (~/project/node_modules/koa-compose/index.js:42:32)
    at ~/project/node_modules/koa-router/lib/router.js:372:16
    at dispatch (~/project/node_modules/koa-compose/index.js:42:32)
    at ~/project/node_modules/koa-compose/index.js:34:12
    at dispatch (~/project/node_modules/koa-router/lib/router.js:377:31)
    at dispatch (~/project/node_modules/koa-compose/index.js:42:32)
    at dispatch (~/project/node_modules/koa-router/lib/router.js:353:32)
    at dispatch (~/project/node_modules/koa-compose/index.js:42:32)
    at cors (~/project/node_modules/@koa/cors/index.js:61:38)
    at dispatch (~/project/node_modules/koa-compose/index.js:42:32)
    at default (file://~/project/app/helpers/error.js:3:15)
    at dispatch (~/project/node_modules/koa-compose/index.js:42:32)
    at ~/project/node_modules/koa-body/index.js:148:14
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Steps to Reproduce
Following the example outlined in https://pnp.github.io/pnpjs/concepts/auth-nodejs/#msal-nodejs, I wrote the following code:
```
import { SPDefault } from "@pnp/nodejs";
import { spfi  } from "@pnp/sp";
import { MSAL } from "@pnp/msaljsclient";
import { Configuration, AuthenticationParameters } from "msal";
import { LogLevel, PnPLogging, Logger, ConsoleListener, FunctionListener } from "@pnp/logging";

export async function coolFunction (ctx, next) {  
    let listener = new FunctionListener((entry) => {
        // pass all logging data to console for now
        console.log(entry.message);
    });
    Logger.subscribe(listener);
    Logger.activeLogLevel = LogLevel.Info;

    const configuration = {
        auth: {
            authority: "https://login.microsoftonline.com/<tenant>",
            clientCertificate: {
                thumbprint: "<thumbprint>",
                privateKey: "<key>",
            },
            clientId: "<client id>"
        }
    };

    const authParams = {
        scopes: ["https://<tenant>.sharepoint.com/.default"]
    };

    try {
        const msalConfig = MSAL(
            configuration,
            authParams
        );
        const sp = spfi("https://<tenant>.sharepoint.com").using(
            SPDefault(),
            msalConfig,
            PnPLogging(LogLevel.Info))
    } catch (err) {
        console.log(err);
    }
    await next();
}
```

**Comment by patrick-rodgers** [comment]
This client `import { MSAL } from "@pnp/msaljsclient";` is for use in the browser. You want to [use the node stuff](https://pnp.github.io/pnpjs/getting-started/#authentication).

**Comment by axelvugts** [comment]
Thanks a lot! It works now, using the @azure/msal-node library.
So the example code in the docs at https://pnp.github.io/pnpjs/concepts/auth-nodejs/#msal-nodejs is incorrect. that's unfortunate

**Comment by patrick-rodgers** [comment]
I agree, it is unfortunate. We do our best as an all volunteer group doing this in our spare time, so for sure the docs can always be improved.
