### ISSUE TITLE
Create React App + MSAL + PnPJS

### ISSUE THREAD

**Issue by mpowney** [pnp/pnpjs#2755]
### What version of PnPjs library you are using

3.x

### Minor Version Number

3.17.0

### Target environment

Browser App (Hosted external to Microsoft 365 platform)

### Additional environment details

I'm attempting to use pnpjs on a vanilla Create React App templated project / single-page-app.  I've built the solution to authenticate to Azure Active Directory via the @azure/msal-browser (v2.38.1) and @azure/msal-react (v1.5.10) libraries.

Below is a full list of my package.json dependencies:
```
  "dependencies": {
    "@azure/msal-browser": "^2.38.1",
    "@azure/msal-react": "^1.5.10",
    "@fluentui/react": "^8.110.8",
    "@pnp/nodejs": "^3.17.0",
    "@pnp/queryable": "^3.17.0",
    "@pnp/sp": "^3.17.0",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.5.2",
    "@types/node": "^16.18.38",
    "@types/react": "^18.2.14",
    "@types/react-dom": "^18.2.6",
    "axios": "^1.4.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "typescript": "^4.9.5",
    "web-vitals": "^2.1.4"
  },
```

Node version:
```
mark@LaptopMark:~/Code/project$ node -v
v16.20.1
```

NPM version:
```
mark@LaptopMark:~/Code/project$ npm -v
8.19.4
```

### Question/Request

After I import the pnpjs libraries for the first time, the build fails with the following errors:

```
ERROR in ./node_modules/@azure/msal-node/dist/msal-node.esm.js 3:0-42

Module not found: Error: Can't resolve 'http' in '/home/mark/Code/project/node_modules/@azure/msal-node/dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "http": require.resolve("stream-http") }'
	- install 'stream-http'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "http": false }
```

The same error is repeated for the following libraries:

```
ERROR in ./node_modules/@azure/msal-node/dist/msal-node.esm.js 4:0-26
Module not found: Error: Can't resolve 'https' in '/home/mark/Code/Microsoft 365 Audit - React App/node_modules/@azure/msal-node/dist'

ERROR in ./node_modules/@azure/msal-node/dist/msal-node.esm.js 6:0-28
Module not found: Error: Can't resolve 'crypto' in '/home/mark/Code/project/node_modules/@azure/msal-node/dist'

ERROR in ./node_modules/buffer-equal-constant-time/index.js 4:13-37
Module not found: Error: Can't resolve 'buffer' in '/home/mark/Code/project/node_modules/buffer-equal-constant-time'
```

... and quite a few more

There's also another type of error repeated numerous times for different libraries:

```
ERROR in node:fs
Module build failed: UnhandledSchemeError: Reading from "node:fs" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
    at /home/mark/Code/project/node_modules/webpack/lib/NormalModule.js:838:25
    at Hook.eval [as callAsync] (eval at create (/home/mark/Code/project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Object.processResource (/home/mark/Code/project/node_modules/webpack/lib/NormalModule.js:835:8)
    at processResource (/home/mark/Code/project/node_modules/loader-runner/lib/LoaderRunner.js:220:11)
    at iteratePitchingLoaders (/home/mark/Code/project/node_modules/loader-runner/lib/LoaderRunner.js:171:10)
    at runLoaders (/home/mark/Code/project/node_modules/loader-runner/lib/LoaderRunner.js:398:2)
    at NormalModule._doBuild (/home/mark/Code/project/node_modules/webpack/lib/NormalModule.js:825:3)
    at NormalModule.build (/home/mark/Code/project/node_modules/webpack/lib/NormalModule.js:969:15)
    at /home/mark/Code/project/node_modules/webpack/lib/Compilation.js:1377:12
    at NormalModule.needBuild (/home/mark/Code/project/node_modules/webpack/lib/NormalModule.js:1260:26)
```

... and then the same for the following:

```
ERROR in node:https
Module build failed: UnhandledSchemeError: Reading from "node:https" is not handled by plugins (Unhandled scheme).

ERROR in node:http
Module build failed: UnhandledSchemeError: Reading from "node:http" is not handled by plugins (Unhandled scheme).

ERROR in node:net
Module build failed: UnhandledSchemeError: Reading from "node:net" is not handled by plugins (Unhandled scheme).

ERROR in node:path
Module build failed: UnhandledSchemeError: Reading from "node:path" is not handled by plugins (Unhandled scheme).

ERROR in node:stream
Module build failed: UnhandledSchemeError: Reading from "node:stream" is not handled by plugins (Unhandled scheme).

ERROR in node:url
Module build failed: UnhandledSchemeError: Reading from "node:url" is not handled by plugins (Unhandled scheme).

ERROR in node:util
Module build failed: UnhandledSchemeError: Reading from "node:util" is not handled by plugins (Unhandled scheme).

ERROR in node:zlib
Module build failed: UnhandledSchemeError: Reading from "node:zlib" is not handled by plugins (Unhandled scheme).
```

This only happens when I introduce pnpjs.  I don't understand modules enough to even start to know where to look.  Any guidance would be appreciated, even if it is along the lines of my scenario not supported.

**Comment by bcameron1231** [comment]
Hi! Just to confirm, everything builds fine without importing PnPjs? The errors above imply trying to use server based modules in a browser application. 

When you introduce PnPjs, you mean when you import them into one of your files? What are you importing exactly.

**Comment by mpowney** [comment]
Yes everything builds fine before importing PnPjs.  The package.json libraries in place are the default modules in [create-react-app](https://create-react-app.dev/docs/getting-started). 

The errors only start showing when I insert a reference to my service.  This service is the only place an import to any @pnp modules exists.  Here's what the service looks like (obviously this code is untested because it doesn't build):

```typescript
import { SPDefault } from "@pnp/nodejs";
import { spfi } from "@pnp/sp";
import { Queryable, DefaultParse, BrowserFetchWithRetry } from "@pnp/queryable";
import { DefaultHeaders, DefaultInit, RequestDigest } from "@pnp/sp";
import { getAccessToken } from "../components/Authenticator";

import "@pnp/sp/sites";
import "@pnp/sp/webs";

export function CustomAuth(): (instance: Queryable) => Queryable {
    return (instance: Queryable) => {
        instance.using(
            DefaultHeaders(),
            DefaultInit(),
            BrowserFetchWithRetry(),
            DefaultParse(),
            RequestDigest());
            
        instance.on.auth.replace(async (url: URL, init: RequestInit) => {
            const accessToken = await getAccessToken(`https://${url.host}/.default`);
            init.headers = { ...init.headers, Authorization: `Bearer ${accessToken}` };
            return [url, init];
        });

        return instance;
    };
}


export const getSite = (url: string): Promise<any> => {
    const sp = spfi(url).using(SPDefault()).using(CustomAuth());
    return sp.site();
}
export const getWeb = (url: string): Promise<any> => {
    const sp = spfi(url).using(SPDefault()).using(CustomAuth());
    return sp.web();
}
```

I note in the create-react-app package.json dependencies, there's some libraries for example testing and reporting that might be where for example ```fs``` is coming from. e.g.

```
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
```
... and:

```
    "web-vitals": "^2.1.4"
```

I'll try removing these to see which is the culprit.

**Comment by patrick-rodgers** [comment]
You have `@pnp/nodejs` added, which is for server. You want something from sp module like SPBrowser.

**Comment by mpowney** [comment]
Ah yes - thanks for spotting it
