### ISSUE TITLE
[v2] Issues importing in node js

### ISSUE THREAD

**Issue by patrick-rodgers** [pnp/pnpjs#986]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.0 ]

Please specify what version(s) of SharePoint you are targeting: [   N/A    ]

### Expected / Desired Behavior / Question

Ability to import and use the modules in node js without special steps required.

### Observed Behavior

In our testing before release of v2 we focused on SPFx compatibility and browser usage, our two main use cases and only did cursory testing in node. Because node's support for esnext modules is spotty at best we are now finding cases where the imports aren't behaving as we want across all projects. 

### Steps to Reproduce

Import the package in a node project and don't transpile it before running.

```
export * from "./collections";
^^^^^^

SyntaxError: Unexpected token 'export'
    at Module._compile (internal/modules/cjs/loader.js:895:18)
    at Object..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (c:\github\fasttrack\tools\gsuite-scanner\src\fetch.ts:3:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
```

**Comment by lumayara** [comment]
I am having the same issue. Were you able to solve it?

**Comment by badhonkundu** [comment]
I am getting this error. Using @pnp/nodejs version 2.0.3

Can you please provide the steps to fix the issue in my solution

**Comment by patrick-rodgers** [comment]
Please read [this article on support for nodejs](https://pnp.github.io/pnpjs/nodejs-support/) versions that don't handle es6 modules.
